class AppString {
  final String chatDescrition =
      ''' Here, the <select> tag is used to define the selection menu. Within the <select> tag, you can define the options for the dropdown list using the <option> tag. Each <option> tag represents a single option in the list and includes the value attribute (which is the value associated with the option) and the text or label that is displayed to the user.
For example, in the code above, the select box has four options with values "value1", "value2",Here, the <select> tag is used to define the selection menu. Within the <select> tag, you can define the options for the dropdown list using the <option> tag. Each <option> tag represents a single option in the list and includes the value attribute (which is the value associated with the option) and the text or label that is displayed to the user.
For example, in the code above, the select box has four options with values "value1", "value2", "value3", and "value4", respectively. The text displayed for each option is "Option 1", "Option 2", "Option 3", and "Option 4".
When a user clicks on the select box, they will see the dropdown list of options, and Here, the <select> tag is used to define the selection menu. Within the <select> tag, you can define the options for the dropdown list using the <option> tag. Each <option> tag represents a single option in the list and includes the value attribute (which is the value associated with the option) and the text or label that is displayed to the user.
For example, in the code above, the select box has four options with values "value1", "value2",Here, the <select> tag is used to define the selection menu. Within the <select> tag, you can define the options for the dropdown list using the <option> tag. Each <option> tag represents a single option in the list and includes the value attribute (which is the value associated with the option) and the text or label that is displayed to the user.
For example, in the code above, the select box has four options with values "value1", "value2", "value3", and "value4", respectively. The text displayed for each option is "Option 1", "Option 2", "Option 3", and "Option 4".
When a user clicks on the select box, they will see the dropdown list of options, and can choose one of the options by clicking on it. The selected option's value will be submitted with the form data when the form is submitted.''';

  final String message =
      '''AKNKAJGAJKGBAKJabfjhbafaj the select box, they will see the dropdown list of options, and Here, the <select> tag is used to define the selection menu. Within the <select> tag, you can define the options for the dropdown list using the <option> tag. Each <option> tag represents a single option in the list and includes the value attribute (which is the value associated with the option) and the text or label that is displayed to the user.
For example, in the code above, the select box has four options with values "value1", "value2",Here, the <select> tag is used to define the selection menu. Within the <select> tag, you can define the options for the dropdown list using the <option> tag. Each <option> tag represents a single option in the list and includes the value attribute (which is the value associated with the option) and the text or label that is displayed to the user.
For example, in the code above, the select box has four options with values "value1", "value2", "valu ''';
}
